name: movie_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  lottie: ^3.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  intl: ^0.19.0
  path_provider: ^2.1.1
  flutter_floating_bottom_bar: ^1.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  curved_navigation_bar: ^1.0.3
  provider: ^6.1.1
  image_picker: ^1.0.4
  timezone: ^0.10.0
  timeago: ^3.6.0
  carousel_slider: ^5.0.0
  win32: ^5.0.8
  archive: ^3.4.5

dependency_overrides:
  url_launcher_web: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#ffffff"
    theme_color: "ffffff"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
